services:
  rabbitmq:
    image: rabbitmq:3.10-management
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ./dados:/var/lib/rabbitmq/
    environment:
        - RABBITMQ_DEFAULT_USER=user
        - RABBITMQ_DEFAULT_PASS=password
    networks:
      - microservices-bridge

  restaurant_db:
    image: mysql:8.0.29
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: restaurant_db
      MYSQL_TCP_PORT: 3307
    expose:
      - 3307
    ports:
      - 3307:3307
    networks:
      - microservices-bridge
    volumes:
      - mysql_data_restaurante:/var/lib/mysql

  item_db:
    image: mysql:8.0.29
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: item_db
      MYSQL_TCP_PORT: 3308
    expose:
      - 3308
    ports:
      - 3308:3308
    networks:
      - microservices-bridge
    volumes:
      - mysql_data_item:/var/lib/mysql

  itemservice:
    build: ./ItemService
    environment:
      - ASPNETCORE_URLS=http://+:5001
    ports:
      - '8081:5001'
    networks:
      - microservices-bridge
    depends_on:
      - item_db
      - rabbitmq

  restaurantservice:
    build: ./RestauranteService
    environment:
      - ASPNETCORE_URLS=http://+:5101
    ports:
      - '8080:5101'
    networks:
      - microservices-bridge
    depends_on:
      - restaurant_db
      - rabbitmq

networks:
  microservices-bridge:
    driver: bridge

volumes:
  mysql_data_restaurante:
  mysql_data_item: