services:
  db:
    image: mysql:8.0.29
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: restaurante_db
      MYSQL_TCP_PORT: 3308
    expose:
      - 3308
    ports:
      - 3308:3308
    networks:
      - microservices-bridge
    volumes:
      - mysql_data:/var/lib/mysql

  itemservice:
    build: ./ItemService
    environment:
      - ASPNETCORE_URLS=http://+:5001
    ports:
      - '8081:5001'
    networks:
      - microservices-bridge
    depends_on:
      - db

  restauranteservice:
    build: ./RestauranteService
    environment:
      - ASPNETCORE_URLS=http://+:5101
    ports:
      - '8080:5101'
    networks:
      - microservices-bridge
    depends_on:
      - db


networks:
  microservices-bridge:
    driver: bridge

volumes:
  mysql_data: